---
kind: pipeline
type: docker
name: test

concurrency:
  limit: 1

steps:
  - name: test
    image: node:lts-slim
    commands:
      - npm run setup
      - npm run test:regression
# trigger:
#   event:
#     - pull_request
#     - rollback
#     - merge
